### ISSUE TITLE
Create Bug Report Template

### ISSUE THREAD

**Issue by demilolu** [embrace-call-for-code/outcarcerate-ui#75]
### Background on the problem the feature will solve/improved user experience
Create a Bug Report Template for the Open Sentencing UI repo

### Describe the solution you'd like
Add a .md file to the Github Issues Templates to create a new template

### Tasks 

1. copy the text in the following link:  https://raw.githubusercontent.com/Call-for-Code-for-Racial-Justice/Hacktoberfest/main/.github/ISSUE_TEMPLATE/bug-report-template.md

2. Create a new file in the Open Sentencing UI [.github/ ISSUE_TEMPLATE
](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/tree/main/.github/ISSUE_TEMPLATE) folder
3. Paste the copied text from above into file 
4. name the file:  bug_report_template.md
5. commit the change to your branch and create a pull request 

### Acceptance Criteria
- Bug Report template file is in Open Sentencing UI  [Issue Template folder ](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/tree/main/.github/ISSUE_TEMPLATE)
- As a user, when I click "new issue" in the Open Sentencing UI repository I see an option for the Bug Report Template

**Comment by ok524** [comment]
I would like to take this!

**Comment by demilolu** [comment]
go for it! @ok524

**Comment by demilolu** [comment]
this is done!
